// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQwA1IQ4TO5IWu6_MTJvcvpiiRWEfZLZM',
    appId: '1:168940095850:web:45568a095168a9a1b63d13',
    messagingSenderId: '168940095850',
    projectId: 'chat-app-596fc',
    authDomain: 'chat-app-596fc.firebaseapp.com',
    storageBucket: 'chat-app-596fc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgg-FHLLeH5YrUuuG2Y2dvFArGTrJbSVQ',
    appId: '1:168940095850:android:672c5ffa981cc5aeb63d13',
    messagingSenderId: '168940095850',
    projectId: 'chat-app-596fc',
    storageBucket: 'chat-app-596fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChG5tuib4ws5LFeYtiCAILk7lzcSDK4_8',
    appId: '1:168940095850:ios:373d7628dfc63e3ab63d13',
    messagingSenderId: '168940095850',
    projectId: 'chat-app-596fc',
    storageBucket: 'chat-app-596fc.firebasestorage.app',
    iosBundleId: 'com.example.mychatapp',
  );
}
